### ISSUE TITLE
更新host卡住不动了

### ISSUE THREAD

**Issue by tonshead** [huhamhire/huhamhire-hosts#91]
更新hostlist.data成功后，点击更改host卡住不动，报错的log显示如下：

Traceback (most recent call last):
  File "gui\qdialog_slots.pyo", line 228, in on_MakeHosts_clicked
  File "gui\qdialog_d.pyo", line 205, in make_hosts
  File "gui_make.pyo", line 95, in **init**
  File "util\makehosts.pyo", line 76, in **init**
IOError: [Errno 13] Permission denied: 'hosts'

**Comment by EdwardYuan** [comment]
是 sudo 启动的么？

**Comment by tonshead** [comment]
Win7 系统，管理员身份运行，重启过电脑，关掉了所有的杀毒软件

**Comment by huhamhire** [comment]
可能当前用户对 hosts 文件的 Owner 权限不对，简单点处理的话，直接手动替换吧

**Comment by yuk320** [comment]
我深圳这边 刚进连接OK 但是选择 2 或者 3 更新 或者 下载 都无法获取数据文件信息

**Comment by EdwardYuan** [comment]
用Administrator登录试试呢？ 不行直接手动替换吧
